name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Memberikan izin tulis pada konten repositori

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Set up Git Credentials globally for the entire job.
      - name: Set up Git Credentials
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check Environment Variables
      - name: Check Env
        run: |
          echo "CSV_URL: $CSV_URL"

      # Install MLflow and other necessary Python dependencies.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # Set up Git LFS tracking for the 'mlruns' directory.
      - name: Set up Git LFS tracking
        run: |
          git lfs install
          git lfs track "MLproject/mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true

      # Run the MLflow project.
      # Ini akan membuat mlruns/ di dalam direktori MLproject/
      - name: Run mlflow project
        run: |
          echo "Listing contents of MLproject directory..."
          ls -la MLproject/
          cd MLproject/
          mlflow run . --env-manager=local
          cd ../

      # Save MLflow run artifacts (mlruns) to the GitHub Repository.
      - name: Save mlruns to repo
        run: |
          git add -f MLproject/mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main

      # Upload results to Google Drive.
      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python MLproject/upload_to_gdrive.py
