name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "Latihan-CI/MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Set up Git Credentials globally for the entire job
      - name: Set up Git Credentials
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check Env Variables
      - name: Check Env
        run: |
          echo "CSV_URL: $CSV_URL"

      # Install mlflow and other dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Set up Git LFS tracking for mlruns
      - name: Set up Git LFS tracking
        run: |
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          # Commit file .gitattributes. Gunakan '|| true' untuk mencegah kegagalan
          # jika file sudah di-commit dan tidak ada perubahan.
          git commit -m "Track large files in mlruns with Git LFS" || true

      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local

      # Save mlruns to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main
